# Generated by Django 5.2.1 on 2025-05-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_activity_post_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='标签颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='activity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='status',
        ),
        migrations.AlterField(
            model_name='activity',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='activity_covers/', verbose_name='封面图片'),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='tags',
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=200, verbose_name='活动标题'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='activities', to='community.tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='community.tag', verbose_name='标签'),
        ),
    ]
